name = "jp-lyrics-app"
main = ".open-next/worker.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "jp-lyrics-app"
database_id = "a9b7c22d-16d1-4ae1-b84c-1138d238f293"

[vars]
SPOTIFY_POLL_MODE = "client"
SPOTIFY_REDIRECT_URI = "https://jplrc.gwo.app/api/auth/callback"

[observability]
enabled = true
